### ISSUE TITLE
> I created some Blu-ray videos, but it says "**TSMUXER FINISHED WITH ERROR CODE 11**.

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#746] opened 2023-08-23 17:44 UTC
> I created some Blu-ray videos, but it says "**TSMUXER FINISHED WITH ERROR CODE 11**. It may not play on Sony BDPs500 player, and this is a bug for the issue. Can you fix this error so it will make it successfully function? I think it may help me with this issue. It will work it out so it will successfully keep things going. ![Screenshot from 2023-08-21 05-39-57](https://user-images.githubusercontent.com/40868495/261985997-42d8d220-ce91-44d6-aea4-4fc07e1aaaac.png)

_Originally posted by @donnafaye0323 in https://github.com/justdan96/tsMuxer/issues/740#issuecomment-1686045234_

**Comment by lgoncal** [comment] 2023-08-24 15:50
You're E-AC3 audio has no core. This might not meet spec. If so, nothing to fix

**Comment by donnafaye0323** [comment] 2023-08-24 16:35
**AC-3** is the only Blu-ray audio format supported for muxing audio.

**Comment by lgoncal** [comment] 2023-08-24 18:32
E-AC3 and AC3 are two different audio codecs

**Comment by donnafaye0323** [comment] 2023-08-24 18:50
Does tsmuxer accept 24fps and 1080fps video formats for blu-ray creation?

**Comment by trzyglow** [comment] 2023-08-25 09:26
mpeg2 isn't blu-ray standard, that's why the error message shows. you have to re-encode the video to H.264 or VC-1 for regular blu-rays and H.265 for uhd/4k blu-rays.

**Comment by trzyglow** [comment] 2023-08-25 10:04
> H.264 is a high-quality video codec commonly used in various applications, including video streaming, video conferencing, and Blu-ray discs. It is more modern and a bit more efficient than mpeg-2.

yes, and you can re-encode mpeg2 into H.264 with ffmpeg, which alters the codec under the hood in order to be compliant with blu-ray standard specs.

**Comment by donnafaye0323** [comment] 2023-08-25 10:13
I would use Shutter Encoder to change audio formats with video converting, too!! I love h.264 videos!!

**Comment by donnafaye0323** [comment] 2023-08-25 16:47
> > H.264 is a high-quality video codec commonly used in various applications, including video streaming, video conferencing, and Blu-ray discs. It is more modern and a bit more efficient than mpeg-2.
> 
> yes, and you can re-encode mpeg2 into H.264 with ffmpeg, which alters the codec under the hood; in order to be compliant with blu-ray standard specs.

Why is H.264 video more efficient than mpeg2 nowadays?

**Comment by trzyglow** [comment] 2023-08-25 17:04
> Why is H.264 video more efficient than mpeg2 nowadays?

better compression quality and better color depth via supported pixel formats.
it's (besides VC-1) the only supported codec in the official (regular) blu-ray standard.
outside of the regular standard there is the uhd/4k blu-ray standard which only supports H.265.
(H.264 was officially introduced in 2003, mpeg2 was introduced about 10 years earlier)

generally speaking H.264 is a relatively inefficient codec compared to newer codecs, but it is both blu-ray compliant and extremely common.

you can mux other codecs regarding both video and audio than what is officially supported, but it will most likely not play on a standard blu-ray player.

**Comment by donnafaye0323** [comment] 2023-08-25 17:17
Why is mpeg2 format not blu-ray compliant? Here's the

> > Why is H.264 video more efficient than mpeg2 nowadays?
> 
> better compression quality and better color depth via supported pixel formats. it's (besides VC-1) the only supported codec in the official (regular) blu-ray standard. outside of the regular standard there is the uhd/4k blu-ray standard which only supports H.265. (H.264 was officially introduced in 2003, mpeg2 was introduced about 10 years earlier)
> 
> generally speaking H.264 is a relatively inefficient codec (regarding compression algorithms) compared to newer codecs, but it is both blu-ray compliant and extremely common.
> 
> you can mux other codecs regarding both video and audio than what is officially supported, but it will most likely not play on a standard blu-ray player.
Here's the screen shot of this error code:
![Screenshot from 2023-08-21 15-42-54](https://github.com/justdan96/tsMuxer/assets/40868495/ba1e23e0-a95e-4c29-af05-7d5d6bc3071b)

**Comment by donnafaye0323** [comment] 2023-08-25 17:38
I will be updated for to fix some issues.

**Comment by trzyglow** [comment] 2023-08-25 17:39
i just noticed you are using an outdated version of tsmuxer, this might be a problem long fixed.

**Comment by jcdr428** [comment] 2023-08-26 09:21
Duplicate of #740 - closing.

**Closed by jcdr428** 2023-08-26 09:21 UTC
