### ISSUE TITLE
17-bit XLL storage resolution is not implemented error

### ISSUE THREAD

**Issue by tormento** [justdan96/tsMuxer#311] opened 2020-07-10 09:58 UTC
After demuxing DTS-HDMA from Onward BD, I use FFMPEG to convert to AC3.

I get the error: 17-bit XLL storage resolution is not implemented. Update your FFmpeg version to the newest one from Git.

This leads to shorter AC3 than the original DTS-HDMA.

The same doesn't occur when demuxing using other tools (i,e, MakeMKV and then demux from MKV).

**Comment by jcdr428** [comment] 2020-07-12 18:06
@tormento can you please provide the first 20 mb of DTS-HDMA file produced by tsMuxer, and the same with file produced by MakeMKV.

**Comment by tormento** [comment] 2020-07-12 19:23
> @tormento can you please provide the first 20 mb of DTS-HDMA file produced by tsMuxer, and the same with file produced by MakeMKV.

Unfortunately it happens at the end.

I don't know if DTS-HDMA is a "raw" format I can cut such as m2ts with no problems and it works with no "header". If you have a ftp, I can upload whole files.

**Comment by richardpl** [comment] 2020-07-12 19:30
Yes, share DTS-HDMA samples, this is trivial to fix in ffmpeg decoder.

**Comment by tormento** [comment] 2020-07-14 09:41
I located the error in the 12th of 250MB split files. Notice that the two files are not identical because Onward mpls contains multiple M2TS and the two softwares process gaps in different ways.

Here are the file TSMuxer and MakeMKV files:

[https://www.mediafire.com/file/l1hwc3lqyjvsaa3/Onward_HDMA.rar/file](url)

Here is the log:

`tsMuxeR version git-632b6e4. github.com/justdan96/tsMuxer
Decoding DTS-HD stream (track 1): Bitrate: 1536Kbps  core + MLP data.Sample Rate: 48KHz  Channels: 7.1 (DTS Master Audio 24bit)
DTS-HD stream (track 1): overlapped frame detected at position 00:04:39,199. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:06:13,791. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:09:34,997. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:10:10,783. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:12:38,805. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:17:11,701. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:19:32,511. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:22:33,610. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:24:14,624. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:28:39,808. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:31:17,802. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:31:40,992. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:32:06,933. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:33:04,032. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:34:00,586. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:34:22,485. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:35:24,672. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:36:49,589. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:38:03,957. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:38:23,306. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:39:00,640. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:45:30,943. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:45:50,751. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:48:24,117. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:50:21,066. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:51:32,554. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:56:44,447. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 00:58:28,927. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:05:01,322. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:05:25,055. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:07:08,735. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:16:06,485. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:17:19,434. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:18:26,293. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:20:04,426. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:22:39,039. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:23:00,693. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:30:10,784. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:32:01,685. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:36:00,597. Remove frame.
DTS-HD stream (track 1): overlapped frame detected at position 01:36:23,573. Remove frame.
Flushing write buffer
Demux complete.
Demuxing time: 1 min 43 sec`

**Comment by ValZapod** [comment] 2021-02-11 12:04
I cannot reproduce on your samples. I use latest ffmpeg from here: https://github.com/BtbN/FFmpeg-Builds/releases

**Comment by jcdr428** [comment] 2021-02-14 17:43
@tormento on my side I have transcoded the two provided files to ac3 with ffmpeg, and both ac3 have the exact same length.
I don't think the issue comes from the "17-bit XLL" ffmpeg warning. As you pointed out, tsMuxer and MakeMKV might have different ways of detecting/removing overlapping frames.
What is the exact length (in bytes) of the resulting AC3 file, from tsMuxer and from MakeMKV ?

**Comment by justdan96** [comment] 2021-06-15 13:33
Closing due to age.

**Closed by justdan96** 2021-06-15 13:33 UTC

**Comment by ValZapod** [comment] 2021-06-15 13:37
> Closing due to age.

Files are still there. https://www.mediafire.com/file/l1hwc3lqyjvsaa3/Onward_HDMA.rar/file
