### ISSUE TITLE
some udf errors from udf_test (udf verifier) 

### ISSUE THREAD

**Issue by Randrianasulu** [justdan96/tsMuxer#498] opened 2021-12-03 16:53 UTC
there is interesting application from 2007 called udf verifier

https://www.lscdweb.com/registered/udf_verifier.html

Our user Terje created udf image with tsmuxer from appimage (hopefully recent enough, exact version in output) and run said udf verifier on it.

Some errors were reported. not sure how to paste/attach big logs here, I'll try link to pastebin.

https://paste.debian.net/1221837/

main type of errors seems to be

FID  32  Error: UniqueID:         #00000000
			Bits 0-31 have a value lower than 16,
			UDF 2.3.4.3, 3.2.1.1, 3.3.3.4.

and

FID  42  Error: 1 non-zero byte found in a 2 bytes blank area
		      begin area at RBP 42
			end area at RBP 43
		 first violation at RBP 42, value #04
		 FID Padding field must hold #00 bytes, ECMA 4/14.4.9
		 name: "JAR"

but also

Note: Metadata File and Mirror File extents not far apart, see
		 summary above, UDF 2.2.13.1, UDF 2.50 errata DCN-5106.

Note: Main VDS and Reserve VDS extents not far apart, see
		 summary above, UDF 2.2.3.2, UDF 2.50 errata DCN-5113.
		 Far apart rules for VDS are introduced in UDF 2.50.

Error: Number of AVDPs less than 2: 1, AVDP at 256
	       UDF 2.2.3, 6.10..., 6.13..., 6.14....

**Comment by jcdr428** [comment] 2021-12-03 17:38
@Randrianasulu very interesting. I'll dig into the UDF 2.50 specs to try and understand these errors.

**Comment by jcdr428** [comment] 2021-12-07 07:40
udf_tester logs for ISO output from tsMuxer and ImgBurn, made from the same BDMV:
[tsMuxer.log](https://github.com/justdan96/tsMuxer/files/7666332/tsMuxer.log)
[ImgBurn.log](https://github.com/justdan96/tsMuxer/files/7666331/ImgBurn.log)

The first thing to fix would be the non-zero byte padding in the FID.
Zero-byte padding is written in line 362 of [iso_writer.cpp](https://github.com/justdan96/tsMuxer/blob/master/tsMuxer/iso_writer.cpp#L362)

**Comment by jcdr428** [comment] 2021-12-08 07:47
@Randrianasulu 
``` 
        EFE  file type FILE  UniqueID: #0000000000000000   name: <SysStreamDir>//"*UDF Unique ID Mapping Data"
        EFE  34  icbtag error: Flags Stream bit: 0, expected: 1, see DCN-5152.
```
fixed by commit 281d87f

**Comment by jcdr428** [comment] 2021-12-11 18:01
@Randrianasulu UniqueID errors should be fixed by commit 7d58796.

Please test latest release for UDF2.50 from tomorrow.

**Comment by Randrianasulu** [comment] 2021-12-12 07:31
no errors on short udf anymore! thanks!

**Comment by jcdr428** [comment] 2021-12-12 08:54
@Randrianasulu can you please post a log with errors on long UDF ? Just drag and drop on the console, no need to use paste in

**Comment by Randrianasulu** [comment] 2021-12-13 03:57
@jcdr428 https://cloud.mail.ru/public/4tj4/uF1VPW6Qd

still few errors:

	AVDP at 256	(MVDS: 32, RVDS: 233504)
	First Tag Serial Number: 3
24438527	read block
	AVDP at N-256	(MVDS: 32, RVDS: 24438464)
	AVDP 2   Warning: Tag Descriptor Version: 2.
		 First occurrence of Descriptor Version 2 and 3 mix.
		 Found so far: value 2: 1 time, value 3: 1 time,
		 ECMA-167 3rd edition 3/7.2.2, 4/7.2.2.
	Error: Tag Serial Number changing: 3 -> 1, no disaster
	       recovery support, ECMA 3/7.2.5, 4/7.2.5, UDF 2.3.1.1.
	AVDP error: Volume Descriptor Sequence Extent not equal to
		    the one read in first AVDP
	   Main: length,location: 32768, 32    expected:  32768, 32   
	Reserve: length,location: 32768, 24438464 expected:  32768, 233504
	Using first AVDP
24438783	read block
	AVDP at N	(MVDS: 32, RVDS: 24438464)
	AVDP error: Volume Descriptor Sequence Extent not equal to
		    the one read in first AVDP
	   Main: length,location: 32768, 32    expected:  32768, 32   
	Reserve: length,location: 32768, 24438464 expected:  32768, 233504
	Using first AVDP

	Number of AVDPs: 3, AVDPs at  256,  N-256,  N

====>	Read Main VDS extent:      32, length:  32768
     32	read block
	PVD   VDS Number: 1
	Error: Tag Serial Number changing: 1 -> 3, no disaster
	       recovery support, ECMA 3/7.2.5, 4/7.2.5, UDF 2.3.1.1.
 ==>	Message printed 2 times, ignored from now.

**Comment by Randrianasulu** [comment] 2021-12-13 06:56
additional info from tester (Terje) :

Just to add:

tsmuxer and disc burning with K3b Version 20.04.2 run on openSUSE Leap 15.3
All udf disc tests run on current openSUSE Tumbleweed

and mentione additionally warnings from udfinfo

    udfinfo /dev/sr0 > /run/media/terje/KINGSTON/udfinfo-23_BD50-RE
    udfinfo: Warning: Device '/dev/sr0' is busy, udfinfo may report bogus information
    udfinfo: Warning: Second and third Anchor Volume Descriptor Pointer not found

    udfinfo /dev/sr0 > /run/media/terje/KINGSTON/udfinfo-23_BD5-DVD+RW
    udfinfo: Warning: Device '/dev/sr0' is busy, udfinfo may report bogus information
    udfinfo: Warning: Second and third Anchor Volume Descriptor Pointer not found

===
I hope udfinfo warnings really bogus, due to udf_tester report of all 3 AVDPs..

**Comment by jcdr428** [comment] 2021-12-14 14:02
@Randrianasulu I can't reproduce the issue. Can you post the meta file ?

**Comment by Randrianasulu** [comment] 2021-12-14 14:51
I'll ask Terje for sources (I think he used termuxGUI)

**Comment by Randrianasulu** [comment] 2021-12-14 18:19
@jcdr428 https://cloud.mail.ru/public/FPJ2/viS6rqqrj

or may be just cat'ed from terminal (sorry no easy dnd from Android 10):
$ cat ~/storage/downloads/Browser/dv28_25mbps.meta.txt
MUXOPT --no-pcr-on-video-pid --new-audio-pes --hdmv-descriptors --blu-ray --vbr  --auto-chapters=5 --vbv-len=500
V_MPEG-2, "/run/media/terje/video/BD-M2TS/SD_Blu-ray/dv28_25mbps.mpg", track=224
A_LPCM, "/run/media/terje/video/BD-M2TS/SD_Blu-ray/dv28_25mbps.mpg", track=160
$

**Comment by jcdr428** [comment] 2021-12-14 19:27
Ok, thanks.
Looking at [iso_writer.cpp lines 905](https://github.com/justdan96/tsMuxer/blob/master/tsMuxer/iso_writer.cpp#L905), 912 and 924, I can't see how the first AVDP (Anchor Volume Descriptor Pointer) can be different from the second and the third AVDP.
I need the `dv28_25mbps.mpg` file to be able to reproduce the issue and debug/trace.

**Comment by Randrianasulu** [comment] 2021-12-14 19:48
@jcdr428  sorry for tying your time up with this problem..

can  this procedure be enough for making your own file?

=====================================================


Blu-ray compliant MPEG-2 SD video with LPCM audio
-------------------------------------------------

1) Encode DV to MPEG-2 video and copy PCM audio as is to a VOB/MPG format:

ffmpeg -i dv28.dv -c:v mpeg2video -refs 1 -bf 2 -b:v 25M -maxrate 25M -minrate 25M -bufsize 45M -muxrate 45M -dc 10 -c:a pcm_s16be -f vob dv28.mpg

Verify the streams:

ffmpeg -i dv28.mpg  2>&1 >/dev/null | egrep "Video|Audio"
    Stream #0:0[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x576 [SAR 16:15 DAR 4:3], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0xa0]: Audio: pcm_dvd, 48000 Hz, stereo, s16, 1536 kb/s




you can make dv (dvsd) files with ffmpeg or download some for samples.mplayerhq.hu if i remeber correctly (pond.dv?) 

Also, note we verified already-written (via k3b) disk, not image on hdd

**Comment by jcdr428** [comment] 2021-12-14 19:50
Thanks @Randrianasulu , I'll try this.

**Comment by jcdr428** [comment] 2021-12-15 19:08
@Randrianasulu I believe the errors on AVDP are created by k3b. From https://github.com/KDE/k3b :
```
 - writing ISO9660-CDs and DVDs
   - Joliet/Rockridge support
   - Udf filestructures (no pure Udf so far)
  ```
So unless there are other errors from HDD output, the issue can be closed.

**Closed** 2021-12-19 18:06 UTC
Labels: bug
