### ISSUE TITLE
This Needs An Update To Fix Error Code 11

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#748] opened 2023-08-25 18:04 UTC
To jcdr468:

This need some updates in order to keep it going on the next release:  This **error code 11** may be the cause of using an outdated version of Tsmuxer for muxing mpeg-2 videos for Blu-ray folders and TS files, so this bug will be fixed soon. 

![Screenshot from 2023-08-21 15-42-54](https://github.com/justdan96/tsMuxer/assets/40868495/7c4b492f-aa71-468a-bd5b-93a7d29fbd7e)

**Comment by Hellboy00000** [comment] 2023-08-26 00:24
Please stop opening multiple issue for the same error.

**Comment by jcdr428** [comment] 2023-08-26 09:19
Duplicate of #740 - closing.

**Closed by jcdr428** 2023-08-26 09:19 UTC
