### ISSUE TITLE
Problem with Dolby Atmos audio

### ISSUE THREAD

**Issue by bouchnouk** [justdan96/tsMuxer#256] opened 2020-03-25 02:50 UTC
Hi,

I am getting an error when I try to demux a Dolby Atmos track. With MediaInfo, I see that the audio track is Dolby Atmos type. 
<img width="700" alt="2020-03-24_22-33-52" src="https://user-images.githubusercontent.com/20449937/77496077-86ee6280-6e20-11ea-999b-648c2ebd80b6.png">
<img width="809" alt="2020-03-24_22-36-12" src="https://user-images.githubusercontent.com/20449937/77496088-8fdf3400-6e20-11ea-93f7-72acebf4314c.png">
On tsMuxer, I am getting an error on the opening of the file. 
<img width="1020" alt="2020-03-24_22-34-22" src="https://user-images.githubusercontent.com/20449937/77496150-b1d8b680-6e20-11ea-818e-ede512606740.png">
Then, the first audio track is discarded by tsMuxer.
<img width="1020" alt="2020-03-24_22-34-31" src="https://user-images.githubusercontent.com/20449937/77496174-c2892c80-6e20-11ea-87fe-f181f9ad7649.png">

I don't know if this a bug or if tsMuxer doesn't support Dolby Atmos yet. If this is the case, I apologize in advance.

Thank you.
[John.Wick.Chapter.3.Parabellum.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR.meta.zip](https://github.com/justdan96/tsMuxer/files/4378727/John.Wick.Chapter.3.Parabellum.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR.meta.zip)

**Comment by jcdr428** [comment] 2020-03-25 06:04
@bouchnouk tsMuxer (and mpeg-ts generally) does not accept Dolby Atmos without AC3 core.
The problem is mkvtoolnix removing the AC3 core from Blu-rays. You can recreate a core with eac3to before muxing into txMuxer.

**Comment by bouchnouk** [comment] 2020-03-26 02:26
Thank you for the answer. Sorry, I didn't know that. I tried to find tsMuxer documentation in order to find an answer but I didn't find anything. 

The solution you're giving seems complicated. Anyway, I will try to find eac3to.

Sorry for the "false alarm". By the way, thank you for the outstanding work your team is doing with tsMuxer.

**Comment by justdan96** [comment] 2020-03-26 07:25
The documentation could probably be updated to reflect this information.

**Comment by bouchnouk** [comment] 2020-03-26 23:18
I was not complaining about the documentation. However, your proposition seems very interesting in my humble opinion.

Thank you.

**Comment by jcdr428** [comment] 2020-03-29 13:30
@justdan96 @bouchnouk actually as this is a very common request, there is an enhancement possible: tsMuxer could interleave the TrueHD frames with empty 32kbit ac3 frames so that the track can be muxed / read by an HDMV player.

**Comment by justdan96** [comment] 2020-03-29 19:29
I've updated the documentation with the following commit - until an enhancement comes along: https://github.com/justdan96/tsMuxer/commit/9cb01b30f1494d3bdc598d7e6268b21dd9f6125b

**Comment by bouchnouk** [comment] 2020-03-29 23:58
@jcdr428 Would that have an impact on Atmos sound ? I mean, is it like Dolby Vision with 2 tracks : one for the video signal and the other one hidden contains the HDR information? I know that an Atmos signal needs 2 tracks. By emptying one track, do we lose something useful?

From a user perspective working on macOS, that would be a fantastic enhancement.  

Best Regards.

**Comment by jcdr428** [comment] 2020-03-30 06:07
@bouchnouk the ac3 track is needed only for compatibility reason, as reading TrueHD is not compulsory for Blu-ray players. Adding silence ac3 frames does not change anything to the TrueHD track. Indeed it would be better to transcode the TrueHD to obtain the ac3+thd -which eac3to already does- rather than having an empty track.

**Comment by bouchnouk** [comment] 2020-03-30 23:35
@jcdr428 I understand. For macOS user, eac3to might be difficult to use. For the others, the use of eac3to should not be a problem. It's up to you to decide. But ,in my humble opinion, it seems an interesting enhancement.

Thank you.

**Comment by MarkerB** [comment] 2020-11-26 22:07
I'd love to be able to have tsMuxer read Atmos tracks, but I don't see how what's been discussed in this thread could be right.  I've read over and over again that TrueHD cannot have an AC3 core; that a core is only something DTS-HD has.

Maybe I'm just too thick to get this.

Like... What would the procedure be to create a tsMuxer-readble Atmos track, if I have a "coreless" TrueHD/Atmos track, and an AC3 track?  I don't see that eac3to can do something like this.  I only see that it can "extract" an AC3 core from TrueHD, but I think that's really just transcoding.

**Comment by MarkerB** [comment] 2020-11-27 01:05
I guess I believed a lot of misinformed people about TrueHD not being able to have a core!

The following thread goes into specific detail of how to use eac3to to create a TrueHd/AC3 combo track: [](http://forum.doom9.org/showthread.php?t=163296)

This seemed to work.

**Comment by jcdr428** [comment] 2022-01-21 18:36
Fixed by be59064

**Closed by jcdr428** 2022-01-21 18:36 UTC
Labels: documentation
