### ISSUE TITLE
Nightly build from 2023-04-03-02-03-37 bug - track was not recognised

### ISSUE THREAD

**Issue by galactic76** [justdan96/tsMuxer#699] opened 2023-04-03 20:41 UTC
True.Spirit.2023.2160p.NF.WEB-DL.DDP5.1.Atmos.DV.MP4.x265-DVSUX.mp4

old version shows error at 10% , last Nightly build from 2023-04-03-02-03-37 

shows
track 1 (trackid1) was not recognised and ignored :(
And the film muxing without audio :(

**Comment by galactic76** [comment] 2023-04-03 20:42
You.People.2023.2160p.NF.WEB-DL.DDP5.1.Atmos.DV.MP4.x265-DVSUX.mp4

the same

All DV MP4 files like this :(

**Comment by DreckSoft** [comment] 2023-04-04 10:13
I can confirm there's an issue with some audio tracks. In my case the EAC3 track with 768kbps and Atmos is not recognized. It works in the March 25th build.

![2023-04-04 12_10_08-tsMuxeR GUI git-020cdb0](https://user-images.githubusercontent.com/68750712/229760783-c4f09c47-a1cd-43f9-aa2a-4452053a8b76.png)
![2023-04-04 12_10_56-tsMuxeR GUI git-e78d02f](https://user-images.githubusercontent.com/68750712/229760789-613bdcd7-f50a-47b5-bcd6-d174c1fa19e3.png)

**Comment by jcdr428** [comment] 2023-04-04 14:50
Fixed in tomorrow's release. A lack of parenthesis was creating undefined behavior...

**Comment by DreckSoft** [comment] 2023-04-05 11:44
Seems to be OK again.

**Closed** 2023-04-05 17:01 UTC
