### ISSUE TITLE
Noise is present in the processed image

### ISSUE THREAD

**Issue by OmniSoundsLab** [justdan96/tsMuxer#634] opened 2022-09-03 15:38 UTC
I need to convert m2ts whose audio part is DST-HD to PCM only for the audio part.
The audio part of the following file "before.m2ts" was converted to PCM (00001 _ (1 dts) .wav), and the result "after.m2ts" was obtained.
However, while there was no problem in the original video, 1:17:49 now has some noise in "after".
Does this mean there is a problem with the original file? If there is a defect, I would like you to fix it.

https://17.gigafile.nu/1212-e08155de7c8a6068248e8edc61f2d540

**Comment by jcdr428** [comment] 2022-09-03 18:10
@OmniSoundsLab do the wav and dts-hd have the same noise ?

**Comment by OmniSoundsLab** [comment] 2022-09-03 19:04
@jcdr428 I'm sorry it's confusing. The noise is on the image. I checked with MPC-HC. If you look at after.m2ts, you can see it.

**Comment by jcdr428** [comment] 2022-09-04 08:28
@OmniSoundsLab is it possible to have shorter (<1GB) before and after m2ts ?

**Comment by OmniSoundsLab** [comment] 2022-09-06 14:09
@jcdr428 I used tsMuxer to cut the two files I uploaded earlier between 1:17:30 and 1:18:00.
However, even in the cutting process, there is noise in the same place in "before _ s.m2ts".
Sorry to bother you, but please check "before.m2ts" for original video.

https://6.gigafile.nu/1215-a121984db5046478ba607c768f879a2e

**Comment by jcdr428** [comment] 2022-09-26 20:01
@OmniSoundsLab I have watched "after_s.m2ts" with MPC-HC, I can't find any noise as compared to "before_s.m2ts".

**Comment by OmniSoundsLab** [comment] 2022-10-01 03:06
@jcdr428  Due to my lack of knowledge, video clipping in the binary editor didn't work, but instead I clipped with MKV ToolNix, which produced a short video file with no noise.
When I put it through tsMuxeR again, the noise was reproduced, so I will send it to you.

https://61.gigafile.nu/0109-43db5d8de739f32acc17c1be7ed43057

**Comment by jcdr428** [comment] 2022-10-01 12:20
@OmniSoundsLab No noise created from before2.mkv on my side.
Which version of tsMuxer did you use ?
Can you copy your meta file ?

**Comment by jcdr428** [comment] 2022-10-23 14:53
Could not reproduce the issue with latest release. Closing, can be repoened upon request.

**Closed by jcdr428** 2022-10-23 14:53 UTC
Labels: bug
