### ISSUE TITLE
Muxing m2ts with SRT file error

### ISSUE THREAD

**Issue by damkalan-uth** [justdan96/tsMuxer#89] opened 2019-12-27 15:32 UTC
When adding srt track on .m2ts file (HEVC 2160p HDR, AC3) it produces the following error.
Using Windows 10 

When removing  the Srt from input files it is ok.

![image](https://user-images.githubusercontent.com/59288630/71522828-08406280-28cf-11ea-9539-90935bfe0392.png)

**Comment by justdan96** [comment] 2019-12-27 20:17
If you save the meta file and run it through the tsMuxer CLI do you get the same error?

**Comment by damkalan-uth** [comment] 2019-12-28 00:03
D:\tsMuxer>tsMuxeR.exe 00004_2.meta
tsMuxeR version 2.6.15. github.com/justdan96/tsMuxer
Can't detect stream type

Directory of D:\tsMuxer

28/12/2019  02:01 πμ    <DIR>          .
28/12/2019  02:01 πμ    <DIR>          ..
27/12/2019  06:00 μμ       143.259.648 00004.m2ts
27/12/2019  05:20 μμ             1.380 00004.srt
28/12/2019  02:00 πμ               383 00004_2.meta
27/12/2019  01:08 πμ         3.739.546 tsMuxeR.exe
27/12/2019  01:09 πμ        21.445.632 tsMuxerGUI.exe
               5 File(s)    168.446.589 bytes

**Comment by xavery** [comment] 2019-12-28 00:10
I presume that the error appears because the subtitle line in the meta file contains `fps=0`, which is rejected by the program while attempting to mux.
The reason why `fps=0` appears is *probably* because tsMuxer fails to properly detect the frame rate while running it in single-file mode in order to detect the stream properties : however, I have not yet looked into this in more detail.

**Comment by damkalan-uth** [comment] 2019-12-28 00:14
Well neither CLI works. I forgot i removed SUBs ftom meta file. I ll try with fps edited

**Comment by damkalan-uth** [comment] 2019-12-28 00:19
Manually edited fps value to 23.976 and it worked!

**Comment by xavery** [comment] 2019-12-28 00:20
Okay, this seems to confirm that the issue is probably with how the frame rate is detected while adding streams to the GUI.

**Comment by damkalan-uth** [comment] 2019-12-28 00:22
To help, on video track Frame rate is detected correctly.

**Comment by xavery** [comment] 2019-12-28 00:48
Cannot reproduce with the current master. Could you try the [latest nightly build](https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly/2019-12-27--01-10-05#files) and report if the issue still appears?

**Comment by damkalan-uth** [comment] 2019-12-28 04:18
No it didn't work with  latest nightly build.
However i did the following trick.
After adding the srt file, i selected video track , checked "Change fps:" and selected appropriate value. This value was copied to the srt properties. Then unchecked "Change fps:" and no error occurred.

Tried with 2.6.12 version and srt was given fps with not the above trick. also , This happens regardless if the video is FHD or UHD or mkv or m2ts.

**Comment by damkalan-uth** [comment] 2019-12-28 05:40
if  info.fpsText (Line 1132 - 1142) is set correct then it should be read correct on rez variable on line 1679 (tsmuxerwindow.cpp), shouldn't it?

**Comment by jcdr428** [comment] 2019-12-28 08:32
@xavery not sure the bug is linked to the hdr10 patch, but I have brought a correction for early detection of hevc stream fps in the "Correct TS descriptors" patch pushed yesterday: in hevcStreamReader.cpp line 62, "updateFPS(m_vps, nal, nextNal, 0);"

**Comment by justdan96** [comment] 2019-12-29 08:01
If we push #92 and the issue isn't resolved, perhaps we can just assume that FPS=0 for subtitle tracks means use the FPS from the video track?

**Comment by jcdr428** [comment] 2019-12-29 17:45
@damkalan-uth can you try the [latest build](https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly/2019-12-28--01-09-59#files)?
On my Windows 10, when adding a .srt file to this latest build, the video fps is correctly detected.

**Comment by damkalan-uth** [comment] 2019-12-29 18:39
I just made a new build from master branch. Have you put latest commits on master branch to test them.

**Comment by justdan96** [comment] 2019-12-29 23:30
There's a new nightly build that will be created at 1am UTC tomorrow.

**Comment by jcdr428** [comment] 2019-12-30 15:54
@damkalan-uth do you still have the fps=0 issue with the 30/12 build ?

**Comment by damkalan-uth** [comment] 2019-12-31 20:50
Yes, still have the issue. After adding SRT video dimensions are copied  but fps stays 0

**Comment by darekpro** [comment] 2020-01-02 11:21
Noticed the same problem latest version.

**Comment by jcdr428** [comment] 2020-01-04 08:34
@damkalan-uth could you please cut the first 50MB of your 00006.m2ts with a hex editor (e.g. HxD), zip it with the srt, upload it somewhere and and give the link for download.

**Comment by justdan96** [comment] 2020-01-05 22:18
Would you be able to also supply more screenshots without the muxing window? I've been experimenting and I can't seem to add the subtitles without it adding an FPS parameter.

**Comment by damkalan-uth** [comment] 2020-01-06 01:02
> Would you be able to also supply more screenshots without the muxing window? I've been experimenting and I can't seem to add the subtitles without it adding an FPS parameter.

https://gofile.io/?c=fPBl4O

**Comment by jcdr428** [comment] 2020-01-06 04:42
@damkalan-uth I've tried your files on my Windows 10 with both the w32 and w64 tsMuxer versions, and both correctly detect the fps... I can't find where the bug comes from.
Which Windows 10 version are you running ? Mine is 1909.

**Comment by damkalan-uth** [comment] 2020-01-06 15:19
Windows 10 Pro x64 (November 2019 update) with tsMuxer x64

**Comment by damkalan-uth** [comment] 2020-01-06 15:21
![image](https://user-images.githubusercontent.com/59288630/71827456-f1f18e00-30a8-11ea-8c82-8afd10aa6b10.png)

**Comment by jcdr428** [comment] 2020-01-06 15:47
@damkalan-uth just one thought... have you tried with your files on the PC drive (i.e. not on an external drive) ?

**Comment by jcdr428** [comment] 2020-01-10 22:01
@damkalan-uth @darekpro  Please try the tsMuxer version https://github.com/jcdr428/tsMuxer/actions to see whether the srt bug is fixed.

**Comment by darekpro** [comment] 2020-01-11 07:48
Hello
No still not detecting
![he](https://user-images.githubusercontent.com/58607093/72200905-1229a000-344f-11ea-8ab2-b2d150faf324.jpg)

**Comment by jcdr428** [comment] 2020-01-11 09:42
@darkrepro @damkalan-uth I was getting mad on this bug, couldn't understand why neither @xavery, @justdan96 or I could reproduce it !!!! I just didn't ask the right questions on your PC.

The fact is the three of us work with English locale (decimal = "."). I have changed my Windows locale to "," and can now see the bug !!

@xavery @justdan96, the bug must be in the GUI tsmuxerwindow.cpp from line 147. As I can't debug without Qt5 installed, could you please look at this bug ?

**Comment by xavery** [comment] 2020-01-11 10:05
@jcdr428 Great find. I'll get right to it.

**Comment by xavery** [comment] 2020-01-11 11:13
Okay, this should be fixed in today's nightly build.

**Comment by darekpro** [comment] 2020-01-11 11:16
great :)
![Zrzut ekranu z 2020-01-11 12-16-33](https://user-images.githubusercontent.com/58607093/72203457-2a5be800-346c-11ea-854f-5ca40aa8c627.png)

**Comment by damkalan-uth** [comment] 2020-01-12 03:52
Hello,

I confirm that the bug has been fixed!

Is this locale bug affecting other parts of tsMuxer application also?

**Comment by xavery** [comment] 2020-01-12 10:50
@damkalan-uth Thanks for reporting back. I'm closing this issue in this case.

There are few more places where a similar bug might occur, but these will be taken care of soon.

**Closed by xavery** 2020-01-12 10:50 UTC
Labels: bug
