### ISSUE TITLE
Minor issue concerning Ubuntu 20.10

### ISSUE THREAD

**Issue by leleobhz** [justdan96/tsMuxer#370] opened 2020-11-02 01:53 UTC
Hello!

I'm using tsMuxer with Ubuntu 20.10 with same repo as 20.04, but libicu66 (And the icu source) only exists on 20.04 - as signaled in page https://packages.ubuntu.com/source/focal/icu and in the missing page of https://packages.ubuntu.com/source/groovy/icu

Installing libicu66 manually from Ubuntu mirror worked very well but I dont know if the solution is to tsMuxer provide the libicu or if it support has dropped, if there is any alternative to it.

Thanks!

**Comment by xavery** [comment] 2020-11-02 07:51
Just to clarify : are you using the provided package/binary, or do you compile tsMuxer yourself?

**Comment by xavery** [comment] 2020-11-04 18:16
I wasn't able to reproduce this with a vanilla Ubuntu 20.10 running off the install CD.
tsMuxer doesn't use ICU directly : the only ICU dependency that might exist is the one introduced by Qt, which may be compiled to use ICU in order to better support codepage conversions and provide more information about Unicode characters. However, if there are issues with Qt loading ICU libraries, then the problem lies with the system configuration (or broken package dependencies), not tsMuxer itself.
Compiling the whole program works without any issues if the packages listed in `COMPILING.md` are installed. Running the AppImage package provided on bintray works as well.

In line with the above, I'm closing this issue - please reopen if you have more information to add.

**Comment by leleobhz** [comment] 2020-11-09 18:48
Hello @xavery 

Sorry by the late. I'm using from the repo of 20.04 - since 20.10 isnt ready:

```
root@manauara:~# apt info tsmuxer
Package: tsmuxer
Version: 2.6.16git.1584294704.cfa580e-55.28
Priority: optional
Section: Multimedia
Maintainer: Dan Bryant <daniel.bryant@linux.com>
Installed-Size: 5.274 kB
Depends: libqt5widgets5,libqt5multimedia5,libqt5gui5,libqt5core5a,libstdc++6,libgcc-s1,libc6,libqt5network5,libpulse0,libgl1,libpng16-16,zlib1g,libharfbuzz0b,libicu66,libpcre2-16-0,libdouble-conversion3,libglib2.0-0,libdbus-1-3,libglvnd0,libglx0,libfreetype6,libgraphite2-3,libpcre3,libxcb1,libsystemd0,libwrap0,libsndfile1,libasyncns0,libx11-6,libxau6,libxdmcp6,liblzma5,liblz4-1,libgcrypt20,libflac8,libogg0,libvorbis0a,libvorbisenc2,libbsd0,libgpg-error0
Homepage: https://github.com/justdan96/tsMuxer
Download-Size: 953 kB
APT-Manual-Installed: yes
APT-Sources: https://download.opensuse.org/repositories/home:/justdan96/Ubuntu_debbuild_20.04 ./ Packages
Description: A simple program to mux video to TS/M2TS files or create BD disks
 A transport stream muxer for remuxing/muxing elementary streams,
 EVO/VOB/MPG, MKV/MKA, MP4/MOV, TS, M2TS to TS to M2TS
```

And libicu66 is a direct dependency of the tsmuxer package:

```
root@manauara:~# apt-cache depends tsmuxer | grep icu
  Depende: libicu66
root@manauara:~# 
```

As the time bug got reported, libicu isn't ported to groovy but now its on version 67.1 - and in debian/control of 67 version does not replaces libicu66:

```
Package: libicu67
Architecture: any
Multi-Arch: same
Pre-Depends: ${misc:Pre-Depends}
Depends: ${misc:Depends}, ${shlibs:Depends}
Breaks: openttd (<< 1.8.0-2~), libiculx63 (<< 63.1-5)
Replaces: libiculx63 (<< 63.1-5)
Description: International Components for Unicode
 ICU is a C++ and C library that provides robust and full-featured
 Unicode and locale support.  This package contains the runtime
 libraries for ICU.
```

Within my Ubuntu 20.10 the issue persists:

```
root@manauara:~# LANG=C apt remove libicu66
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libicu66 tsmuxer
0 upgraded, 0 newly installed, 2 to remove and 3 not upgraded.
After this operation, 38.8 MB disk space will be freed.
Do you want to continue? [Y/n] y
Requesting to save current system state
Successfully saved as "autozsys_x38gnb"
(Reading database ... 311376 files and directories currently installed.)
Removing tsmuxer (2.6.16git.1584294704.cfa580e-55.28) ...
Removing libicu66:amd64 (66.1-2ubuntu2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libc-bin (2.32-0ubuntu3) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
ZSys is adding automatic system snapshot to GRUB menu
root@manauara:~# LANG=C apt-get install tsmuxer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tsmuxer : Depends: libicu66 but it is not installable
E: Unable to correct problems, you have held broken packages.
root@manauara:~# LANG=C dpkg -i libicu66_66.1-2ubuntu2_amd64.deb 
Selecting previously unselected package libicu66:amd64.
(Reading database ... 311352 files and directories currently installed.)
Preparing to unpack libicu66_66.1-2ubuntu2_amd64.deb ...
Unpacking libicu66:amd64 (66.1-2ubuntu2) ...
Setting up libicu66:amd64 (66.1-2ubuntu2) ...
Processing triggers for libc-bin (2.32-0ubuntu3) ...
root@manauara:~# LANG=C apt-get install tsmuxer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  tsmuxer
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 0 B/953 kB of archives.
After this operation, 5274 kB of additional disk space will be used.
Requesting to save current system state
Successfully saved as "autozsys_zl2vg8"
Selecting previously unselected package tsmuxer.
(Reading database ... 311368 files and directories currently installed.)
Preparing to unpack .../tsmuxer_2.6.16git.1584294704.cfa580e-55.28_amd64.deb ...
Unpacking tsmuxer (2.6.16git.1584294704.cfa580e-55.28) ...
Setting up tsmuxer (2.6.16git.1584294704.cfa580e-55.28) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
ZSys is adding automatic system snapshot to GRUB menu
root@manauara:~# 
```

As the package major version changes the package name, I suspect a new version (With a different debian/control Requirements with libicu67 and their dev packages) need to be created.

Thanks and sorry by my late.

**Comment by xavery** [comment] 2020-11-09 20:25
Oh snap, I forgot about the OBS packages that we provide. I guess it would be best to simply add 20.10 to the available repositories. Pinging @justdan96 since he's maintaining these.

**Comment by justdan96** [comment] 2020-11-09 22:13
Bit of an odd one but I can't seem to "block" dependencies so I will just try to get the 20.10 repo up and running.

**Comment by xavery** [comment] 2020-11-09 23:05
Yup, I'm quite sure adding 20.10 to the available versions should fix this so that the package is built against the Qt packages available in 20.10. Just summing up in case I wasn't being clear :
* `libqt5core5a` in [20.04](https://packages.ubuntu.com/focal/libqt5core5a) depends on [`libicu66`](https://packages.ubuntu.com/focal/libicu66).
* `libqt5core5a` in [20.10](https://packages.ubuntu.com/groovy/libqt5core5a) depends on [`libicu67`](https://packages.ubuntu.com/groovy/libicu67).
* Because the packages in OBS are built on the systems that they're supposed to run on (and quite rightly so), the generated package depends on `libicu66` which isn't available in 20.10, presumably because of an API-/ABI-incompatible update, and all packages depending on ICU in 20.10 depend on `libicu67` instead of `libicu66`.

**Comment by justdan96** [comment] 2020-11-15 18:50
Unfortunately this is blocked until Ubuntu debbuild functionality for Ubuntu 20.10 is added in the openSUSE Open Build Service. I posted a message to IRC to ask when it would be available but no response yet.

**Comment by justdan96** [comment] 2020-11-16 11:21
That was a quick turnaround from the openSUSE guys: https://build.opensuse.org/package/binaries/home:justdan96/tsMuxer/Ubuntu_debbuild_20.10

Please try out this package and repo and let me know how it goes.

**Comment by justdan96** [comment] 2020-11-16 11:25
@xavery Looks like we need to update the README to mention we support versions 18.04 - 20.10 of Ubuntu

**Comment by xavery** [comment] 2020-11-16 15:24
Works great in my Ubuntu VM. I'll update the documentation and close the issue after @leleobhz confirms that things are OK on their end as well.

**Comment by leleobhz** [comment] 2020-11-16 16:13
Hello!

```
root@manauara:~# export LANG=C
root@manauara:~# apt purge tsmuxer 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  tsmuxer*
0 upgraded, 0 newly installed, 1 to remove and 21 not upgraded.
After this operation, 5274 kB disk space will be freed.
Do you want to continue? [Y/n] y
Requesting to save current system state
Successfully saved as "autozsys_e0tfun"
(Reading database ... 368499 files and directories currently installed.)
Removing tsmuxer (2.6.16git.1584294704.cfa580e-55.28) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
ZSys is adding automatic system snapshot to GRUB menu
root@manauara:~# apt autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
root@manauara:~# apt remove libicu6
libicu66  libicu67  
root@manauara:~# apt remove libicu6
libicu66  libicu67  
root@manauara:~# apt remove libicu66 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libicu66
0 upgraded, 0 newly installed, 1 to remove and 21 not upgraded.
After this operation, 33.6 MB disk space will be freed.
Do you want to continue? [Y/n] y
Requesting to save current system state
Successfully saved as "autozsys_rauita"
(Reading database ... 368491 files and directories currently installed.)
Removing libicu66:amd64 (66.1-2ubuntu2) ...
Processing triggers for libc-bin (2.32-0ubuntu3) ...
ZSys is adding automatic system snapshot to GRUB menu
root@manauara:~# echo 'deb https://download.opensuse.org/repositories/home:/justdan96/Ubuntu_debbuild_20.10 ./' > /etc/apt/sources.list.d/tsmuxer.list 
root@manauara:~# apt update
Hit:1 https://linux.teamviewer.com/deb stable InRelease
Hit:2 https://dl.winehq.org/wine-builds/ubuntu groovy InRelease                                                                                                                                           
Hit:3 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                              
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease                                                                                                                                            
Hit:5 http://archive.ubuntu.com/ubuntu groovy InRelease                                                                                                                                                   
Ign:6 http://dl.google.com/linux/earth/deb stable InRelease                                                                                                                                               
Hit:7 http://br.archive.ubuntu.com/ubuntu groovy InRelease                                                                                                                                                
Hit:8 http://download.zerotier.com/debian/buster buster InRelease                                                                                                                                         
Get:9 http://br.archive.ubuntu.com/ubuntu groovy-updates InRelease [108 kB]                                                                                                                               
Hit:10 http://archive.canonical.com/ubuntu groovy InRelease                                                                                                                                               
Hit:11 http://dl.google.com/linux/earth/deb stable Release                                                                                                                                                
Hit:12 http://ppa.launchpad.net/berglh/pulseaudio-a2dp/ubuntu groovy InRelease                                                                                                                            
Hit:13 http://download.opensuse.org/repositories/home:/ColinDuquesnoy/xUbuntu_20.04  InRelease                                                                                                            
Hit:14 http://br.archive.ubuntu.com/ubuntu groovy-backports InRelease                                                                                                                                     
Hit:15 http://download.opensuse.org/repositories/home:/codestation/xUbuntu_19.10  InRelease                                                                                                               
Get:16 http://security.ubuntu.com/ubuntu groovy-security InRelease [108 kB]                                                                          
Hit:17 http://deb.anydesk.com all InRelease                                                                                              
Hit:18 http://ppa.launchpad.net/inkscape.dev/stable/ubuntu groovy InRelease                                                              
Hit:20 http://ppa.launchpad.net/linuxuprising/java/ubuntu groovy InRelease                                                                                
Get:21 http://br.archive.ubuntu.com/ubuntu groovy-updates/restricted Sources [4496 B]
Get:22 https://download.opensuse.org/repositories/home:/justdan96/Ubuntu_debbuild_20.10 ./ InRelease [1185 B]      
Get:23 http://br.archive.ubuntu.com/ubuntu groovy-updates/main Sources [43.6 kB]                                     
Get:24 http://br.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages [115 kB]        
Get:25 http://br.archive.ubuntu.com/ubuntu groovy-updates/main i386 Packages [42.0 kB]
Get:26 http://br.archive.ubuntu.com/ubuntu groovy-updates/main Translation-en [31.9 kB]
Get:27 http://br.archive.ubuntu.com/ubuntu groovy-updates/main amd64 DEP-11 Metadata [13.6 kB]
Get:28 http://br.archive.ubuntu.com/ubuntu groovy-updates/restricted i386 Packages [3908 B]    
Get:29 http://br.archive.ubuntu.com/ubuntu groovy-updates/restricted amd64 Packages [42.9 kB]
Get:30 http://br.archive.ubuntu.com/ubuntu groovy-updates/restricted Translation-en [7620 B]
Get:31 http://br.archive.ubuntu.com/ubuntu groovy-updates/universe i386 Packages [22.6 kB]   
Get:32 http://br.archive.ubuntu.com/ubuntu groovy-updates/universe amd64 Packages [31.4 kB]
Get:33 http://br.archive.ubuntu.com/ubuntu groovy-updates/universe amd64 DEP-11 Metadata [6768 B]
Hit:34 http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu groovy InRelease
Hit:35 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu groovy InRelease                  
Get:36 https://download.opensuse.org/repositories/home:/justdan96/Ubuntu_debbuild_20.10 ./ Packages [772 B]
Hit:37 http://ppa.launchpad.net/ppsspp/testing/ubuntu cosmic InRelease             
Hit:38 http://ppa.launchpad.net/remmina-ppa-team/remmina-next-daily/ubuntu groovy InRelease
Hit:39 http://ppa.launchpad.net/stebbins/handbrake-releases/ubuntu focal InRelease
Hit:40 http://ppa.launchpad.net/webupd8team/y-ppa-manager/ubuntu groovy InRelease
Hit:41 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease
Fetched 583 kB in 4s (130 kB/s)                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
25 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@manauara:~# apt install tsmuxer 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  tsmuxer
0 upgraded, 1 newly installed, 0 to remove and 25 not upgraded.
Need to get 960 kB of archives.
After this operation, 5354 kB of additional disk space will be used.
Get:1 https://download.opensuse.org/repositories/home:/justdan96/Ubuntu_debbuild_20.10 ./ tsmuxer 2.6.16git.1584294704.cfa580e-55.1 [960 kB]
Fetched 960 kB in 3s (380 kB/s)  
Requesting to save current system state
Successfully saved as "autozsys_d4wvlh"
Selecting previously unselected package tsmuxer.
(Reading database ... 368475 files and directories currently installed.)
Preparing to unpack .../tsmuxer_2.6.16git.1584294704.cfa580e-55.1_amd64.deb ...
Unpacking tsmuxer (2.6.16git.1584294704.cfa580e-55.1) ...
Setting up tsmuxer (2.6.16git.1584294704.cfa580e-55.1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
ZSys is adding automatic system snapshot to GRUB menu
root@manauara:~# tsmuxer -v
tsMuxeR version 2.6.16-dev. github.com/justdan96/tsMuxer

root@manauara:~# 
```

And for GUI:

![image](https://user-images.githubusercontent.com/201189/99278205-84a4a280-280d-11eb-93ad-4ce770b8f90f.png)

Ready to close! Thank so much @xavery  and @justdan96 !

**Comment by xavery** [comment] 2020-11-16 17:08
README updated, closing.

**Closed by xavery** 2020-11-16 17:08 UTC
Labels: documentation
