### ISSUE TITLE
Unsupported media type 135 for AVCHD/Blu-ray muxing

### ISSUE THREAD

**Issue by mfraser** [justdan96/tsMuxer#364] opened 2020-10-22 17:30 UTC
Trying to remux a ts file into a blu-ray ISO, I'm getting the above error.

tsMuxeR version git-2d378f2. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
B-pyramid level 2 detected. Shift DTS to 3 frames
Decoding E-AC3 (DD+) stream (track 2): Bitrate: 768Kbps (core 0Kbps) Sample Rate: 48KHz Channels: 5.1
Processed 1786 video frames
Flushing write buffer
Creating Blu-ray stream info and seek index
Creating Blu-ray playlist
Finalize ISO disk

General
ID                                       : 1 (0x1)
Complete name                            : /home/mfraser/Videos/Misc/LG Dolby Comparison 4K Demo.ts
Format                                   : MPEG-TS
File size                                : 294 MiB
Duration                                 : 1 min 15 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 32.7 Mb/s

Video
ID                                       : 33 (0x21)
Menu ID                                  : 2 (0x2)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.04.06, BL+EL+RPU
Codec ID                                 : 36
Duration                                 : 1 min 14 s
Bit rate                                 : 30.3 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.152
Stream size                              : 269 MiB (92%)

Audio
ID                                       : 35 (0x23)
Menu ID                                  : 2 (0x2)
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : 135
Duration                                 : 1 min 15 s
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -948 ms
Stream size                              : 6.91 MiB (2%)
Service kind                             : Complete Main

**Comment by jcdr428** [comment] 2020-10-22 22:31
@mfraser this is not a bug. Pure E-AC3 audio is not a Blu-ray media type, the E-AC3 must be interleaved with AC3.

**Comment by xterran** [comment] 2020-12-11 09:29
> @mfraser this is not a bug. Pure E-AC3 audio is not a Blu-ray media type, the E-AC3 must be interleaved with AC3.

It is not true. Do not mislead users. E-AC3, also known as Dolby Digital Plus, is the standard audio codec for Blu-Ray.
Read the specifications:
https://en.wikipedia.org/wiki/Blu-ray#Audio
For this reason, E-AC3 is used without problems when using MUX on an old version of tsmuxer, for example 1.10.6.
Problems with the e-AC3 codec on the current version (from December 7, 2020) - this is a bug that needs to be fixed.

**Comment by jcdr428** [comment] 2020-12-12 15:19
@xterran Wikipedia is not the specs. Below is an excerpt of the specs: Blu-ray DD+ is composed of interleaved AC3 frames (bsid=6 or 8) and E-AC3 frames (bsid=16).

<img width="251" alt="Blu-ray spec 9 9 5" src="https://user-images.githubusercontent.com/56721609/101987598-6bb8d100-3c95-11eb-884b-ba3bc23de37e.png">

**Comment by xterran** [comment] 2020-12-15 23:24
@jcdr428 
> Blu-ray DD+ is composed of interleaved DD (AC3) frames and DD+ (E-AC3) frames
Ok. And what?
As I see DD+ used in Blu-ray. So Tsmuxer must work with it. And Tsmuxer 1.10.6 (old) work normaly. 2.6.12 - not work.
What is the obvious conclusion?

**Comment by jcdr428** [comment] 2020-12-19 13:17
Obvious conclusion is 1.10.6 was accepting non-compliant E-AC3 streams for Blu-ray muxing, and this bug has been fixed by Roman in 2.6.12.
Why would you want to be able to output non-compliant Blu-rays ?

**Comment by xterran** [comment] 2020-12-19 15:32
1. Do you want to say that an article about such a well-known standard as blu-ray on wikipedia (which is read by tens (if not hundreds) of millions of people a year) contains incorrect information? Such an event is almost impossible. otherwise, the error would have been noticed and corrected 15 years ago (and then another 10,000 times annually). why didn't you file a complaint about the article (with links to evidence)? Anyone can do it. But no one did.
2. i did not delve into the specification, but even on your screenshots it is clearly written in clause 9.9.5: "synchronization frames of dolby digital plus audio streams". with a further detailed description of the synchronization process itself. If the Blu-Ray standard was incompatible with the audio format (as it is not compatible, for example, with mp3), then the specification would explicitly state: the format is not compatible with the Blu-Ray standard and synchronization is not possible. But it doesn't say that.

As you can see, my logic is simple and consistent. And both points refute your theory.

**Comment by xavery** [comment] 2020-12-19 19:19
Adding my 2¢ as a third party observer who does not know anything about Blu-ray specs : the paragraph you cited (grossly out of context, I may add) is *exactly* why what you want to be implemented does not follow the specification.

The beginning of the paragraph clarifies that a "Dolby Digital Plus audio stream" (as far as the BD specs are concerned) means :

> A Dolby Digital Plus audio stream shall always contain **one independent substream with a substream ID of '0'** and **one dependent substream with a substream ID of '0'**.

What the substreams should contain is specified by the subparagraphs that precede the meaning of `bsid` and other abbreviations, and their expected values in each substream :

> **Independent substream 0** consists of a sequence of **Dolby Digital** synchronization frames.

> **Dependent substream 0** consists of a sequence of **Dolby Digital Plus** synchronization frames.

Therefore, DD+ (E-AC3) is indeed supported by BD, but needs to be interleaved with DD (AC3) because the spec says so. That does not mean that DD+ is not supported : there's just a peculiar requirement about how it should be presented in the Blu-ray transport streams.

**Comment by xterran** [comment] 2020-12-19 20:07
> Therefore, DD+ (E-AC3) is indeed supported by BD
It's very good that we found out.
Now the next question is: which version of Tsmuxer can correctly determine whether a DD+ track meets the special requirements of the BD specification.
Let's say I have a DD+ file and it is normally muxed in 1.10.6 and then works on players, but it is not muxed in version 2.6.12.
What does this mean?

**Comment by jcdr428** [comment] 2020-12-19 20:09
@xterran Please supply a link to download the DD+.

**Comment by DreckSoft** [comment] 2021-01-03 15:24
I encountered the same issue. What I did as a workaround. Mux one time without the DD+ track and a second time with the DD+ track and then edit the playlist file (the one from the first mux) with BDEdit. 

In general: Why don't you just offer a "Create non standard-compliant Blu-Ray" option. I sometimes mux MP2 soundtracks (from SAT recordings) using the workaround above. I just also want to keep the original non-reencoded stream. With such an option, it would be a lot easier.

**Comment by xterran** [comment] 2021-01-04 21:58
BD https://rutracker.org/forum/viewtopic.php?t=5669914
+ Rus DUB netflix E-AC3 5.1
+ eng commentary E-AC3 2.0
https://rutracker.org/forum/viewtopic.php?t=5901932
or https://yadi.sk/d/eIslGwioCChalw

The old muxer 1.10.6. collects normally.
New muxer 2.6.12 (December 7, 2020) buggy: once you collect something normal, next time - no sound. It seems that the muxer does not remember the position of the "Downconvert E-AC3 to AC3" checkbox. For correct results, the new assembly must be maintained in a new window of the muxer. Check it out.

**Comment by jcdr428** [comment] 2021-01-05 19:40
@xterran can you please open another issue, thanks.

**Comment by xterran** [comment] 2021-01-06 18:55
@jcdr428
Rus DUB netflix E-AC3 5.1
eng commentary E-AC3 2.0
added to BD. What is not clear?
Why do I need a new issue?

**Comment by jcdr428** [comment] 2021-01-06 19:10
@xterran I still don't follow: first link is a BD with DTS-HDMA audio, second link is a mkv with E-AC3 audio. What is your point, what is the relation with the current issue ?

**Comment by xterran** [comment] 2021-01-08 14:48
@jcdr428, what do you do on this forum if you don't understand what tsmuxer is and what it was created for?
https://yadi.sk/i/L3l0rdb8Qr1xWA

**Comment by jcdr428** [comment] 2021-01-13 16:39
@xavery this "non-issue" can be closed.

**Closed** 2021-05-10 20:07 UTC
