### ISSUE TITLE
Importing MTS Videos But Finishing With Tsmuxer Error-02

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#799] opened 2023-10-29 13:34 UTC
I added a short .mts video but it still says TSMUXER Error.  Here's a snapshot of this error:
![Screenshot from 2023-10-29 09-24-15](https://github.com/justdan96/tsMuxer/assets/40868495/6592bf0b-6526-41cf-9d0a-6658303b2113)
 
Only videos have to be 1 to 2 hours long and must be authored on Blu-Ray.  The two HD standards that all BluRay players and HD televisions support are **1280 x 720 at 60fps** (50 fps in PAL countries) progressive and **1920 x 1080 at 60/50fps interlaced** (60 fields, 30 complete frames per second).

I hope that this video importing issue will  be fixed.

**Comment by lgoncal** [comment] 2023-10-29 14:35
Link to mts files causing issues?
Not some mp4 files

**Comment by donnafaye0323** [comment] 2023-10-29 15:21
> Link to mts files causing issues? Not some mp4 files
Here's a snapshot of  this video from an USB Drive:

![Adding MTS Files to Blu-Ray-Sample ](https://github.com/justdan96/tsMuxer/assets/40868495/a14a00c5-197c-467b-a129-820de0aecf57)
 MP4 Video File extensions are NOT supported in Blu-ray discs.

**Comment by lgoncal** [comment] 2023-10-29 15:31
`MP4 Video File extensions are NOT supported in Blu-ray discs.`
No kidding.
Snapshot is useless, post link to actual mts causing error so devs can see what the problem

**Comment by donnafaye0323** [comment] 2023-10-29 17:54
Here's an example of an .MTS File that causes an error:
[Circle-10292023-1242.mts.zip](https://github.com/justdan96/tsMuxer/files/13198803/Circle-10292023-1242.mts.zip)
 
I hope the developers can fix this issue soon.

**Comment by donnafaye0323** [comment] 2023-10-29 17:57
> `MP4 Video File extensions are NOT supported in Blu-ray discs.` No kidding. Snapshot is useless, post link to actual mts causing error so devs can see what the problem

 This is a . MTS  Video file in a ZIP Container:

[Circle-10292023-1242.mts.zip](https://github.com/justdan96/tsMuxer/files/13198816/Circle-10292023-1242.mts.zip)

**Comment by lgoncal** [comment] 2023-10-29 18:46
Text formats included in mts (EIA-608, EIA-708) are not supported.
Plus, your file shows corruption.
When the two text formats are removed by remuxing to mkv, tsMuxer loads it  fine.
Vdub2 also crashes on your mts file

**Comment by donnafaye0323** [comment] 2023-10-29 19:46
> Text formats included in mts (EIA-608, EIA-708) are not supported. Plus, your file shows corruption. When the two text formats are removed by remuxing to mkv, tsMuxer loads it fine. Vdub2 also crashes on your mts file

Here's a Video Clip For Blu-Ray Muxing:

[Sample Video-01.webm](https://github.com/justdan96/tsMuxer/assets/40868495/dcb1b243-6846-496a-8b9c-558720de205a)

**Comment by lgoncal** [comment] 2023-10-29 20:48
And this sample is corrupt as well, and webm is not supported.
just remux to mkv

**Comment by donnafaye0323** [comment] 2023-10-29 21:50
> And this sample is corrupt as well, and webm is not supported. just remux to mkv/

Here's A  Video Sample For Blu-Ray Authoring

https://github.com/justdan96/tsMuxer/assets/40868495/fde0f70d-2031-48ce-8d67-bf7415f0d944

I Have No MKV or MTS Video Samples. Stop Telling me about this error positively.

**Comment by lgoncal** [comment] 2023-10-29 21:54
`I Have No MKV or MTS Video Samples`
@jcdr428 
You have to decide if this is a communication issue or a troll issue

**Comment by donnafaye0323** [comment] 2023-10-29 22:06
> `I Have No MKV or MTS Video Samples` @jcdr428 You have to decide if this is a communication issue or a troll issue

This is a communications issue. Everything works very well with no issues at all.

**Comment by donnafaye0323** [comment] 2023-10-29 22:09
@jcdr428 
Everything went out well by importing long videos and muxing to Blu-ray. It was great!!

**Comment by jcdr428** [comment] 2023-11-12 13:58
> @jcdr428 Everything went out well by importing long videos and muxing to Blu-ray. It was great!!

@donnafaye0323 so the issue is solved ?

**Comment by donnafaye0323** [comment] 2023-11-12 14:52
Yes. This is wonderful!! Soon I will have record-able Blu-rays to make and enjoy.

**Comment by jcdr428** [comment] 2023-11-12 19:32
Ok thanks, closing.

**Closed by jcdr428** 2023-11-12 19:32 UTC
