### ISSUE TITLE
tsMuxerGUI fails to build in Debian 11 after 1a1b771

### ISSUE THREAD

**Issue by SugaryHull** [justdan96/tsMuxer#497] opened 2021-11-29 23:12 UTC
Qt version: 5.15.2
Kernel version: 5.10.70-1

Problem: tsMuxerGUI fails to build on Debian 11 for me. tsMuxer itself is unaffected by this and still builds.

I suspect it was the change to model-view for font settings. All commits after 1a1b771e1462f823a8fd4a5c29d82be8e78eba19 fail to build with the following error:
``` In file included from /home/alexander/src/tsMuxer/tsMuxerGUI/tsmuxerwindow.cpp:28:
/home/alexander/src/tsMuxer/tsMuxerGUI/ui_tsmuxerwindow.h: In member function ‘void Ui_TsMuxerWindow::setupUi(QWidget*)’:
/home/alexander/src/tsMuxer/tsMuxerGUI/ui_tsmuxerwindow.h:1043:41: warning: ‘void QPlainTextEdit::setTabStopWidth(int)’ is deprecated [-Wdeprecated-declarations]
 1043 |         memoChapters->setTabStopWidth(20);
      |                                         ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QPlainTextEdit:1,
                 from /home/alexander/src/tsMuxer/tsMuxerGUI/ui_tsmuxerwindow.h:25,
                 from /home/alexander/src/tsMuxer/tsMuxerGUI/tsmuxerwindow.cpp:28:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qplaintextedit.h:179:24: note: declared here
  179 |     QT_DEPRECATED void setTabStopWidth(int width);
      |                        ^~~~~~~~~~~~~~~
/home/alexander/src/tsMuxer/tsMuxerGUI/tsmuxerwindow.cpp: In constructor ‘TsMuxerWindow::TsMuxerWindow()’:
/home/alexander/src/tsMuxer/tsMuxerGUI/tsmuxerwindow.cpp:340:9: error: ‘class Ui::TsMuxerWindow’ has no member named ‘fontSettingsTableView’
  340 |     ui->fontSettingsTableView->setModel(fontSettingsModel);
      |         ^~~~~~~~~~~~~~~~~~~~~
/home/alexander/src/tsMuxer/tsMuxerGUI/tsmuxerwindow.cpp:341:9: error: ‘class Ui::TsMuxerWindow’ has no member named ‘fontSettingsTableView’
  341 |     ui->fontSettingsTableView->horizontalHeader()->resizeSection(0, 65);
      |         ^~~~~~~~~~~~~~~~~~~~~
/home/alexander/src/tsMuxer/tsMuxerGUI/tsmuxerwindow.cpp:342:9: error: ‘class Ui::TsMuxerWindow’ has no member named ‘fontSettingsTableView’
  342 |     ui->fontSettingsTableView->horizontalHeader()->resizeSection(1, 185);
      |         ^~~~~~~~~~~~~~~~~~~~~
/home/alexander/src/tsMuxer/tsMuxerGUI/tsmuxerwindow.cpp:345:13: error: ‘class Ui::TsMuxerWindow’ has no member named ‘fontSettingsTableView’
  345 |         ui->fontSettingsTableView->setRowHeight(i, 20);
      |             ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [tsMuxerGUI/CMakeFiles/tsMuxerGUI.dir/build.make:151: tsMuxerGUI/CMakeFiles/tsMuxerGUI.dir/tsmuxerwindow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:210: tsMuxerGUI/CMakeFiles/tsMuxerGUI.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by xavery** [comment] 2021-11-30 06:57
It looks like `ui_tsmuxerwindow.h` wasn't regenerated in your build. Have you tried running qmake/cmake from scratch?

**Comment by SugaryHull** [comment] 2021-11-30 17:22
This was from a fresh build directory

**Comment by xavery** [comment] 2021-12-01 07:55
Sorry, can't reproduce this with my Debian 11 system : the build works just fine.
Also, our automated builds start out with a clean directory as well and use Qt 5.15.2 too, so we would've caught this failure before the commit in question was even merged.

**Comment by SugaryHull** [comment] 2021-12-01 14:42
I'll try building in a chroot environment. I suspect that it's my Debian install that's at fault.

**Comment by SugaryHull** [comment] 2021-12-01 19:04
It builds just fine when running qmake and make in the tsMuxerGUI directory on my main Debian install. Running CMake after that didn't return the same error, so I'll go ahead and close this issue. Apologies for the false alarm

**Closed** 2021-12-01 19:04 UTC
