### ISSUE TITLE
Code is not 64-bit clean

### ISSUE THREAD

**Issue by blenheimears** [justdan96/tsMuxer#9] opened 2019-09-16 01:14 UTC
A 64-bit build of tsMuxeR currently creates corrupt but still playable output. For example, the audio and/or video will have glitches. The issue appears to be in the demuxing code rather than the muxing code, as the output is correct if tsMuxeR is given raw elementary streams (eg. .h264, .ac3, .wav files). Additionally, subtitle rendering does not work at all on 64-bit builds. I have determined that this is due to a failure to convert the name of the font to UTF-32, only the first character is converted. I have not determined why the string fails to convert.

**Comment by filler56789** [comment] 2019-09-16 04:35
Hi there. PERHAPS this post on Doom9's forum has the solution (or workaround) to the problem,
I think it's worth a try:

https://forum.doom9.org/showthread.php?p=1882862#post1882862

**Comment by justdan96** [comment] 2019-09-17 07:19
My understanding is the 64-bit code won't compile without "-fpermissive" - but perhaps this is actually masking the issues you are describing. I'll try to document the errors that appear if you compile without "-fpermissive" to see if they correspond to the issues you describe.

The issue must be in utf8Converter.cpp - is the build you are using Windows or Linux? Also if you could include some instructions to reproduce the issue with some open source video like https://peach.blender.org/ or http://www.valkaama.com/index.php?page=sources that would really help with the process.

**Comment by filler56789** [comment] 2019-09-17 13:25
@justdan96 — yeah, the file bitStream.cpp should be rewritten for good. According to what I have found on the web, that kind of conversion [under "normal" circumstances] is not tolerated by the 64-bit compiler(s) because of the "loss of precision" thing. But I myself am not qualified for the task.

**Comment by blenheimears** [comment] 2019-09-18 02:10
I don't have any issues compiling the code on a 64-bit machine, even without -fpermissive, but the resulting binary does not work correctly. I am using Linux, specifically Ubuntu 18.04. I'll post an example of the corrupt output for Big Buck Bunny tomorrow.

**Comment by blenheimears** [comment] 2019-09-19 01:27
I've uploaded a file (the first two minutes of Big Buck Bunny) that will trigger the audio bug when processed with a 64-bit build of tsMuxeR. I have also included in the archive the corrupted output of the 64-bit tsMuxer, as well as the correct output of a 32-bit build. I used the m2ts muxing option to create these files, but the bug occurs in the other modes as well, such as Blu-ray ISO. This is Blu-ray quality HD video, so each file is slightly over 500 MB in size once unpacked from the archive.

bbb-2mins.mkv - The original file
bbb-2mins-broken.m2ts - Output of 64-bit tsMuxer with audio glitches
bbb-2mins-correct.m2ts - Correct output of 32-bit tsMuxer

https://drive.google.com/file/d/1Dhb9lkvT7B9cUzsYU0gypAJsgvPrHCBq/view?usp=sharing

**Comment by justdan96** [comment] 2019-09-19 08:13
Sorry can you also share the exact command line parameters you used to produce those files? I want to make sure my own tests are exactly the same as yours.

**Comment by blenheimears** [comment] 2019-09-22 02:10
I used the GUI. The mode I used was M2TS Muxing. I didn't change any options from the defaults.

**Comment by xavery** [comment] 2019-10-23 20:32
I tried reproducing this issue with 64-bit builds made by GCC 9.2.0 and Clang 9.0.0, in both debug and release modes, and none of the builds were capable of producing a TS file with audio glitches like the one you attached. Similarly like you, I used the GUI to start the muxing process and did not change any defaults : the only thing I did was clicking "add" the source MKV file and then "Start muxing".
Playing back the TS files made by these builds in VLC doesn't produce any audio artefacts, while playing back "bbb-2mins-broken.m2ts" does.
However, none of the TS files produced by my builds are exactly the same as "bbb-2mins-correct.m2ts", as verified by calculating an MD5 sum.

**Comment by justdan96** [comment] 2019-10-24 15:21
Interesting results. I will dig out my Linux VM with Qt installed and will produce a new tsMuxerGUI. Then I'll produce tsMuxer in a Linux container with Clang and GCC. I will trace the output from the GUI and try to produce my own results and compare against the existing hashes. 

This might be the first step to a testing suite.

**Comment by justdan96** [comment] 2019-10-24 20:40
With my first run through tsMuxerGUI I get the same output as @xavery 

```
62342b056d37e44fae4e48161d6208bf  bbb-2mins-gcc-linux.m2ts
```

I've saved the meta file as well, I'll see if I can get the output of a Windows build for comparison.

For reference the meta file is:

```
MUXOPT --no-pcr-on-video-pid --new-audio-pes --vbr  --vbv-len=500
V_MPEG-2, "/mnt/shared/tsmuxer-bbb-test/bbb-2mins.mkv", track=1, lang=und
A_AC3, "/mnt/shared/tsmuxer-bbb-test/bbb-2mins.mkv", track=2, lang=und
```

**Comment by justdan96** [comment] 2019-10-25 12:12
I've created another Windows build of tsMuxer, from this branch: https://github.com/justdan96/tsMuxer/pull/17

The MD5 sum is still exactly the same:
```
62342b056d37e44fae4e48161d6208bf  bbb-2mins-from-mxe-meta.m2ts
```

@blenheimears can you please try creating a build from the branch specified in the pull request and see if you get MD5 sums matching mine and @xavery ?

**Comment by justdan96** [comment] 2019-10-26 09:01
I'll keep testing the MD5 sums with new builds but so far I haven't been able to reproduce this. 

I will also think about how to create a small testing suite to make these problems easier to catch.

**Comment by justdan96** [comment] 2019-10-30 19:31
Seeing as I can't reproduce the issue I will be closing this issue

**Closed** 2019-10-30 19:31 UTC
Labels: bug
