### ISSUE TITLE
random delay is added to audio tracks

### ISSUE THREAD

**Issue by ettorps** [justdan96/tsMuxer#346] opened 2020-09-18 16:48 UTC
It seems that commit 78cfc4c14910af6b260ac3ed5a764fb537698102 introduced a bug where a random delay is added to all audio tracks.
Using the exact same .meta file (without any timeshift= option), tsMuxeR from Linux nightly build 2020-09-08--02-21-37 works fine (mode Blu-Ray v3 ISO), but tsMuxeR from Linux nightly build 2020-09-13--02-21-33 adds the delay (also mode Blu-Ray v3  ISO).

I did not test the Windows builds.
I also did not check if the delay is also added to subtitle tracks.

**Comment by jcdr428** [comment] 2020-09-19 06:50
Sorry, I did not test enough before pushing #337 .
All should be fixed with patch #347 .

**Comment by jcdr428** [comment] 2020-09-20 21:48
@ettorps please confirm whether the issue is fixed, thanks.

**Comment by ettorps** [comment] 2020-09-21 09:53
yes, the audio delay issue is fixed

I tested the ISO creation with option --constant-iso-hdr from commit bb3263f9fc01dcdf850b827b78e58a0f4b8d7a14 (before introduction of this issue) and commit 6fb457b961734fbdf20d95fc65623563480bc176 (your fix) and the ISO files differed. Is this expected because of other changes in the meantime?

**Comment by jcdr428** [comment] 2020-09-21 18:27
@ettorps if there is a message "b-pyramid detected" then yes, the files will be different.

**Comment by Stalem360** [comment] 2020-09-22 06:29
What does B-pyramid level 1 detected. Shift DTS to 2 frames or B-pyramid level 2 detected. Shift DTS to 3 frames exactly do?

**Comment by jcdr428** [comment] 2020-09-22 19:28
@Stalem360 this is the frame depth, i.e. how many frames the DTS / decoded picture order count is behind the PTS / encoded picture order count. The more B-frames between the P-frames, the higher the frame depth.

@ettorps please close the issue if fixed, thanks.

**Closed** 2020-09-23 06:59 UTC
Labels: bug
