### ISSUE TITLE
Importing PVR Recordings from USB Flash Drive But Stack Smashing Error

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#791] opened 2023-10-17 20:12 UTC
I imported this PVR recording from my USB Drive,  but it says "stack smashing detected" and it was terminated.
Here's a screenshot of this error:
[my-ublock-backup_2023-09-10_17.17.57.txt](https://github.com/justdan96/tsMuxer/files/12950753/my-ublock-backup_2023-09-10_17.17.57.txt)

This issue is to be fixed as soon as possible.

**Comment by jcdr428** [comment] 2023-10-17 21:16
Duplicate of issue #792.

**Closed by jcdr428** 2023-10-17 21:16 UTC
