### ISSUE TITLE
Problem importing video into Tsmuxer: Error track 0 was not recognized

### ISSUE THREAD

**Issue by bouchnouk** [justdan96/tsMuxer#389] opened 2021-01-08 04:00 UTC
Hi,

Since 2-3 days, I am having problems with Tsmuxer when I import a video from a MKV file. I am getting an error message: "Track 0 was not recognized and ignored". This message never occurred before with previous version of Tsmuxer. Please see the images. Has a bug sneaked in? 

I am on MacOS Catalina 10.15.7 using Tsmuxer version of January 7th, 2021. 

Thanks in advance.

<img width="1256" alt="2021-01-07_22-47-07" src="https://user-images.githubusercontent.com/20449937/103972503-21fbc300-513b-11eb-9096-2bbb179f7585.png">
<img width="1256" alt="2021-01-07_22-47-26" src="https://user-images.githubusercontent.com/20449937/103972505-232cf000-513b-11eb-92de-c37d209d922b.png">
<img width="948" alt="2021-01-07_22-58-15" src="https://user-images.githubusercontent.com/20449937/103972862-f9c09400-513b-11eb-9e19-35a59d4f12cf.png">
[National Lampoon's Christmas Vacation 1989 1080p Blu-ray Remux AVC DTS-HD MA 2.0 - KRaLiMaRKo.meta.zip](https://github.com/justdan96/tsMuxer/files/5785132/National.Lampoon.s.Christmas.Vacation.1989.1080p.Blu-ray.Remux.AVC.DTS-HD.MA.2.0.-.KRaLiMaRKo.meta.zip)

**Comment by jcdr428** [comment] 2021-01-10 21:49
@bouchnouk should be fixed by #391, please wait for this fix to be merged.

**Comment by bouchnouk** [comment] 2021-01-11 00:04
Understood. Thank you.

Best Regards.

**Comment by darekpro** [comment] 2021-01-11 10:20
Heh funny because just I wanted write the same thread with problem.

**Comment by jcdr428** [comment] 2021-01-11 17:12
@bouchnouk @darekpro could you please confirm that the issue is solved with [latest nightly](https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly/2021-01-11#files) ?

**Comment by darekpro** [comment] 2021-01-11 17:21
Yes ofc for my is fine now.

**Comment by bouchnouk** [comment] 2021-01-12 00:03
Hi,

Problem solved. That was fast! Thank you very much.

Best Regards.

**Comment by jcdr428** [comment] 2021-01-12 17:04
@bouchnouk y'a pas de quoi ;) Please close the issue, thanks.

**Closed** 2021-01-13 03:00 UTC
