### ISSUE TITLE
Windows Build Broken Since 8/31/2020

### ISSUE THREAD

**Issue by antgiant** [justdan96/tsMuxer#335] opened 2020-09-08 21:16 UTC
I just tried the x64 version of the Windows nightly builds and working backwards from the most current version it took till the 8/31/2020 build before it would run on my Windows 10 Machine. All of the ones more recent than that would not do anything. Looking in Task manager the executable loaded and then immediately, and silently closed. It did not throw any error messages or write to any log files that I could find. Additionally, the memory used in Task Manager never went above 56K. So, I think it crashed at some really early start up state.

**Comment by jcdr428** [comment] 2020-09-09 05:27
@antgiant there has been three commits pushed on 02/09, after the 31/8 nightly release and before the 02/09 nightly, in the following order:

99e193c: https://github.com/justdan96/tsMuxer/suites/1129918356/artifacts/16095060
ba409fa: https://github.com/justdan96/tsMuxer/suites/1130160362/artifacts/16101624
c139668: https://github.com/justdan96/tsMuxer/suites/1134511353/artifacts/16208279

Can you please try each, and advise which version crashes your PC.

**Comment by xavery** [comment] 2020-09-09 21:28
There have been no meaningful changes to the build scripts or the Docker container that could influence the build. For the record, the latest builds work fine on my Windows 10 machine, both x86 and x64. Running the GUI makes Windows activate the SmartScreen alert, but other than that it works okay.
@antgiant Please test the builds @jcdr428 linked and report back.

**Comment by jcdr428** [comment] 2020-09-20 21:49
@antgiant please confirm whether the issue is fixed, thanks.

**Comment by jcdr428** [comment] 2020-09-22 19:30
@xavery no answer from @antgiant I believe we can close this issue and antgiant can re-open if needed.

**Closed** 2020-09-22 19:51 UTC

**Comment by antgiant** [comment] 2020-10-11 01:07
Sorry I didn't respond earlier. You are correct that this turned out to be machine specific. My AV was being especially evil to me. Sorry for the false report.
