### ISSUE TITLE
w64-nightly 30-04 problem with wine on debian server

### ISSUE THREAD

**Issue by roboluzzo** [justdan96/tsMuxer#303] opened 2020-05-29 16:03 UTC
Hi justdan96, I am trying to use tsMuxeR on a Debian server via wine, but, while older versions are starting, the latest releases do not start. Can you give me some advice?
Thanks, Roberto.
![tsMuxeR problem on debian with wine](https://user-images.githubusercontent.com/35394610/83280281-b0d45480-a1d6-11ea-851b-3bcd7b20e932.jpg)

**Comment by xavery** [comment] 2020-05-29 17:45
You do know that we have a Linux build, right?

**Comment by roboluzzo** [comment] 2020-05-30 12:30
Yes i know, but appimage from 09-05 on my debian server won't start

**Comment by xavery** [comment] 2020-05-30 16:32
> Yes i know, but appimage from 09-05 on my debian server won't start
> 
> /tmp/.mount_tsMuxeaNdjoq/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_tsMuxeaNdjoq/usr/bin/../lib/libsndfile.so.1)

This is caused by the Docker image used to build the Linux using Ubuntu 19.04, which has a newer version of the C library, and the produced binaries in turn have dependencies to that version. I have [reported this](https://github.com/justdan96/tsmuxer_build/issues/1), but I don't think that went anywhere because there was simply never a real reason to do anything about it.

Anyhow, while I can't say for sure why the previous versions worked, I'm pretty sure that this is caused by Qt's platform support somewhere down the line, as this is the only thing which might request GLX support, which is [not really supported with X2Go](https://wiki.x2go.org/doku.php/wiki:development:glx-xlib-workaround).

I guess it would be easiest for you to just compile your own build in this case, unless it's impossible for you to get the needed development packages on that machine.

**Comment by justdan96** [comment] 2020-06-09 20:19
You could try the build for Debian from: https://build.opensuse.org/repositories/home:justdan96/tsMuxer

**Comment by justdan96** [comment] 2020-08-29 14:14
Closing this as alternative has been given and the issue is quite aged now

**Closed** 2020-08-29 14:15 UTC
Labels: question
