### ISSUE TITLE
Joining Files But Finishing With Error Code 11

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#744] opened 2023-08-23 17:00 UTC
Every time I join m2ts files for muxing and Blu-ray folders,  it says "T**SMUXER FINISHED WITH ERROR CODE 11**." It went to 89% and nothing happened.
Here's the picture of this problem:

[Screenshot from 2023-08-23 12-39-35](https://github.com/justdan96/tsMuxer/assets/40868495/ff304c19-d9e1-4dcd-b9fc-26a380543c08

"As previously stated, tsMuxeR only outputs to TS and M2TS containers." Would you fix this video-joining error issue so it might work properly?  What is error code 11 and how can you do something about it? Blu-rays have resolutions **of 720p 24fps and 60fps**, and **1080p 24fps.**  This problem will be solved immediately.

Thank you for this issue.

**Comment by jcdr428** [comment] 2023-08-26 09:22
Duplicate of #740 - closing.

**Closed by jcdr428** 2023-08-26 09:22 UTC
