### ISSUE TITLE
Making Blu-Ray Videos With Unsuccessful Muxing

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#741] opened 2023-08-21 10:20 UTC
I made some Blu-ray folders but it says **TSMUXER FINISHED WITH ERROR 11.**  It can't play on my Sony BDPs500 player.
Can you help fix this bug so it will make it work successfully. Thanks for this issue, and I am sure it helps is a lot.
![Screenshot from 2023-08-21 05-39-57](https://github.com/justdan96/tsMuxer/assets/40868495/6af4276c-4284-48e3-a233-ff497c59bb0b)

**Comment by jcdr428** [comment] 2023-08-26 09:24
Duplicate of #740 - closing.

**Closed by jcdr428** 2023-08-26 09:24 UTC
